# Generated by Django 2.1.15 on 2020-03-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugarNome', models.CharField(max_length=250)),
                ('lugarRank', models.IntegerField(max_length=10)),
                ('lugarTipo', models.CharField(max_length=50, null=True)),
                ('lugarLatitude', models.CharField(max_length=50, null=True)),
                ('lugarLongitude', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(max_length=10)),
                ('pessoaNome', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=100)),
                ('userSenha', models.CharField(max_length=100)),
                ('userToken', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
